name: pyseqrna-0.2
channels:
  - conda-forge
  - bioconda
  - defaults
  - r

dependencies:
  - python=3.12
  - r-base
  - r-essentials
  - flexbar
  - trimmomatic
  - trim-galore
  - star
  - hisat2
  - bowtie2
  - subread
  - htseq
  - samtools
  - bamtools
  - bedtools
  - pip
  - matplotlib
  - rpy2
  - sortmerna
  - bioconductor-deseq2
  - bioconductor-edger
